language: node_js
node_js:
- '4.1'
deploy:
  provider: heroku
  api_key:
    secure: hOabzFRYfAY1DHGuTyKaFCcMtekFulKXSoNzt3yS1OTDsz4Woe5xQjYyMXGfn+qttOVSoFpr537bC1guICuzDyogNoxji9tNDOlBQECWiz6ZCv8Q6fo7tlIDri+kT6LwlJievQ4bEzlV1fNS6x6Sg2gYhs9LVzL30IkjH7m19JldVPJNZ7R8tgsjqFXQ0k+Y3VFrYscE9M1jGRiHmv2WBI53Hrpm3w6VQTeLaCcaVycqafBnvG8hk9ijilmAJF2IAIaaXOOT3RCk/fIDLci6tgQjY6UoZFb/NDUf5+4GZnbiBGjNM1QirhuO+MPm1QIcizA6WT/UZjRFvfnbC8lm210mN3pZ+JEPzUco+vc5jEHAnfsKpR4bSyp2zP+AdY1W8nZ7TMjcG8ghvS8ZOrKcqmd3rHrR2TcUhVauMmLeL35Rvf5qGeWvByzyxWkSX5+ipFnx0Q382wtVAxZjyY63jnWuEZgBOwK1hMpoxRAq4r4ZbxAv8U+aM0YiVV4HcL0V6+1SzbAkWmc2S55I9qINteD8TMsP1WIhyZjkPxH4RgSd8f6e5Ot0hNax+CFv7Y3ru6otbIVuwTPAUf2Abz80yibitytMM2uH5ZVX6udI3eKXXQEYit/4Gcd3Kp7xpViLXkaBXBxumsZM1MQC3JTSTDovxXdIl3QqZB9rLrBEi6I=
  app: tilesfordays