language: node_js
node_js:
- '4.1'
deploy:
  provider: heroku
  api_key:
    secure: Lj5ea2IMSGtwH8wA4EwfXb0IzePFumt9TyB0730TZfl5a2Gn7deJJcoBgVmSsUo88fJuTmBxJCXuS5pJwfkb1qrn4SZdyFJz1L6PPnemh/0iFAgqdTX3iEjw8DfoCHv3U/d3A1tgrLFNjWw5oe5QZ859PjrZUG0ZDTMjm7c/WUZtx4+Q2n5J65SuvY4NVtmjQrcn6EitVQzyn2HsRbVP+rwDa5p/AYSnMbU3QM0aDpBULfxAYoVcB5MJQLANC4OfHU91fYwbLN5C7+sf8vGRUtj96ETsXf1PK2RJn/yOsZ08OIc3gDKtCLDXMSOx5LUZ1hCrrmjOaPswFNiagKvcDxNYc3ErPdC4mGGoWeFRDhLE21ioP5UO6XGLh66G371qEdCDSLwQwHLatcZSPpZqlJ1cc3p47wYqk7Vzi+pFQXET1X3/njKCIHCUKArhE5lMLI8cMHsrvQ1FWlXcNI/dle6WwX35/w53dj1yJ7RxF2Sh9H+lsuO4mT0RLdXlyoviGSbweEBakNMga8MbQ8jZloE8BS/oKEeGDQ9gm7aAvAPEuOgiO/7OvFEx7NknIQqIM5CY+JK7iBp61DjnDpE0Aj8PHLlfuKXZYia41xkRQZSFAmHOFL+KWMI/H7Lb7Xva+egP/aCuhjDCkRgktDzyISh3ItfZYzo15ifM9iDnO5w=
  app: tilesfordays